name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install global env tools
        uses: jdx/mise-action@v2
        with:
          experimental: true
          mise_toml: |
            [tools]
            node = "20"
            go = "latest"
            java = "latest"

      - name: Install claat
        shell: bash
        run: |
          go install github.com/googlecodelabs/tools/claat@latest

      - name: Install project deps and build
        run: |
          cd site
          npm ci
          npm run build

      - name: Include CNAME file
        shell: bash
        run: |
          echo "codelabs.viam.com" > ./site/dist/CNAME

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
