name: Test Build

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install global env tools
        uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tools]
            node = "20"
            go = "latest"
            java = "latest"

      - name: Install claat
        shell: bash
        run: |
          go install github.com/googlecodelabs/tools/claat@latest

      - name: Check JAVA_HOME
        shell: bash
        run: |
          echo $JAVA_HOME

      - name: Install project deps and build
        shell: bash
        run: |
          cd site
          npm install
          npm install google-closure-compiler-java google-closure-compiler-linux
          npm run build
