name: Test Build

on:
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install global env tools
        uses: jdx/mise-action@v2
        with:
          log_level: debug
          mise_toml: |
            [tools]
            node = "20"
            go = "latest"

      - name: Install claat
        shell: bash
        run: |
          go install github.com/googlecodelabs/tools/claat@latest

      - name: Install project deps and build
        shell: bash
        run: |
          cd site
          npm ci
          npm run build
